<?php
declare(strict_types=1);

/*
Solution Title: ASX Historic Summary
Solution Summary: Displays curated ASX historic summary artifacts generated by the overlay pipeline.
Solution Tag: asx-historic-csv
*/

function asx_curated_root(): string
{
  return '/app/data/curated/asx/historic';
}

function asx_summary_files(string $root): array
{
  if (!is_dir($root)) {
    return [];
  }

  $files = [];
  $iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS)
  );

  foreach ($iterator as $fileInfo) {
    if (!$fileInfo instanceof SplFileInfo || !$fileInfo->isFile()) {
      continue;
    }

    $name = $fileInfo->getFilename();
    if (!str_ends_with($name, '_summary.json')) {
      continue;
    }

    $files[] = $fileInfo->getPathname();
  }

  sort($files);
  return $files;
}

function asx_read_summary(string $path, string $root): ?array
{
  $raw = file_get_contents($path);
  if ($raw === false) {
    return null;
  }

  $decoded = json_decode($raw, true);
  if (!is_array($decoded)) {
    return null;
  }

  $decoded['_relative_path'] = ltrim(str_replace($root, '', $path), DIRECTORY_SEPARATOR);
  return $decoded;
}

function asx_format_value(mixed $value): string
{
  if ($value === null) {
    return 'null';
  }
  if (is_bool($value)) {
    return $value ? 'true' : 'false';
  }
  if (is_float($value)) {
    return rtrim(rtrim(number_format($value, 6, '.', ''), '0'), '.');
  }
  if (is_int($value)) {
    return (string) $value;
  }
  return (string) $value;
}

$root = asx_curated_root();
$summaryFiles = asx_summary_files($root);
$summaries = [];

foreach ($summaryFiles as $path) {
  $summary = asx_read_summary($path, $root);
  if ($summary !== null) {
    $summaries[] = $summary;
  }
}

$page_title = 'ASX Historic Summary';
$page_description = 'Curated ASX historic summary artifacts mirrored for local PHP display.';

ob_start();
?>
<h1>ASX Historic Summary</h1>
<h3><a href="/index.php">Services</a> &nbsp; <a href="/health.php">Health</a> &nbsp; <a href="/solutions.php">Solutions</a></h3>

<p>
  Curated summaries are read from <code><?= htmlspecialchars($root) ?></code>.
</p>

<?php if ($summaries === []): ?>
  <div class="card">
    <h2>No Curated Summaries</h2>
    <p>No ASX curated summary JSON files were found.</p>
  </div>
<?php else: ?>
  <?php foreach ($summaries as $summary): ?>
    <div class="card">
      <h2><?= htmlspecialchars((string) ($summary['job_name'] ?? 'Unnamed job')) ?></h2>
      <p><strong>Curated file:</strong> <code><?= htmlspecialchars((string) ($summary['_relative_path'] ?? '')) ?></code></p>

      <table class="tiers-compare">
        <thead>
          <tr>
            <th style="width: 220px;">Field</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <tr><td><strong>Raw prefix</strong></td><td><code><?= htmlspecialchars((string) ($summary['raw_prefix'] ?? '')) ?></code></td></tr>
          <tr><td><strong>Conformed target</strong></td><td><code><?= htmlspecialchars((string) ($summary['conformed_target'] ?? '')) ?></code></td></tr>
          <tr><td><strong>Curated target</strong></td><td><code><?= htmlspecialchars((string) ($summary['curated_target'] ?? '')) ?></code></td></tr>
          <tr><td><strong>Row count</strong></td><td><?= htmlspecialchars(asx_format_value($summary['row_count'] ?? null)) ?></td></tr>
          <tr><td><strong>Column count</strong></td><td><?= htmlspecialchars(asx_format_value($summary['column_count'] ?? null)) ?></td></tr>
        </tbody>
      </table>

      <h2>Columns</h2>
      <table class="tiers-compare">
        <thead>
          <tr>
            <th>Column</th>
            <th style="width: 220px;">Dtype</th>
            <th style="width: 180px;">Null count</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach (($summary['columns'] ?? []) as $column): ?>
            <tr>
              <td><code><?= htmlspecialchars((string) $column) ?></code></td>
              <td><?= htmlspecialchars(asx_format_value($summary['dtypes'][$column] ?? null)) ?></td>
              <td><?= htmlspecialchars(asx_format_value($summary['null_counts'][$column] ?? null)) ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

      <h2>Numeric Stats</h2>
      <?php if (empty($summary['numeric_stats']) || !is_array($summary['numeric_stats'])): ?>
        <p>No numeric stats available.</p>
      <?php else: ?>
        <table class="tiers-compare">
          <thead>
            <tr>
              <th>Column</th>
              <th>Count</th>
              <th>Mean</th>
              <th>Min</th>
              <th>Max</th>
              <th>Sum</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($summary['numeric_stats'] as $column => $stats): ?>
              <tr>
                <td><code><?= htmlspecialchars((string) $column) ?></code></td>
                <td><?= htmlspecialchars(asx_format_value($stats['count'] ?? null)) ?></td>
                <td><?= htmlspecialchars(asx_format_value($stats['mean'] ?? null)) ?></td>
                <td><?= htmlspecialchars(asx_format_value($stats['min'] ?? null)) ?></td>
                <td><?= htmlspecialchars(asx_format_value($stats['max'] ?? null)) ?></td>
                <td><?= htmlspecialchars(asx_format_value($stats['sum'] ?? null)) ?></td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<?php
$content = ob_get_clean();
require __DIR__ . '/../inc/layout.php';
