services:
  airflow-webserver:
    build:
      context: .
      dockerfile: overlay_asx_historic_csv/docker/airflow/Dockerfile
    volumes:
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

  airflow-scheduler:
    build:
      context: .
      dockerfile: overlay_asx_historic_csv/docker/airflow/Dockerfile
    volumes:
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

  jupyter:
    build:
      context: .
      dockerfile: overlay_asx_historic_csv/docker/jupyter/Dockerfile
    environment:
      S3_ENDPOINT_URL: "http://minio:9000"
      AWS_ACCESS_KEY_ID: "${MINIO_ROOT_USER:-minioadmin}"
      AWS_SECRET_ACCESS_KEY: "${MINIO_ROOT_PASSWORD:-minioadmin}"
      AWS_DEFAULT_REGION: "us-east-1"
    volumes:
      - ./config:/home/jovyan/config:ro
      - ./scripts:/home/jovyan/scripts:ro
      - ./data:/home/jovyan/data

  php:
    environment:
      ENABLED_SOLUTION_TAGS: "asx-historic-csv"
    volumes:
      - ./data:/app/data:ro
