services:
  airflow-webserver:
    build:
      context: .
      dockerfile: ./overlay_hello_world/docker/airflow/Dockerfile
    image: apache/airflow:2.10.3-hello-world
    environment:
      HELLO_WORLD_CONFIG_DIR: /opt/airflow/config
      HELLO_WORLD_LOCAL_DATA_DIR: /opt/airflow/data
      HELLO_WORLD_SAMPLE_DIR: /opt/airflow/data/sample/hello_world
    labels:
      org.opencontainers.image.title: "hello-world-overlay"

  airflow-scheduler:
    build:
      context: .
      dockerfile: ./overlay_hello_world/docker/airflow/Dockerfile
    image: apache/airflow:2.10.3-hello-world
    environment:
      HELLO_WORLD_CONFIG_DIR: /opt/airflow/config
      HELLO_WORLD_LOCAL_DATA_DIR: /opt/airflow/data
      HELLO_WORLD_SAMPLE_DIR: /opt/airflow/data/sample/hello_world
    labels:
      org.opencontainers.image.title: "hello-world-overlay"

  jupyter:
    build:
      context: .
      dockerfile: ./overlay_hello_world/docker/jupyter/Dockerfile
    image: jupyter/minimal-notebook:hello-world
    environment:
      HELLO_WORLD_CONFIG_DIR: /home/jovyan/config
      HELLO_WORLD_LOCAL_DATA_DIR: /home/jovyan/data
      HELLO_WORLD_SAMPLE_DIR: /home/jovyan/data/sample/hello_world

  php:
    environment:
      ENABLED_SOLUTION_TAGS: "${ENABLED_SOLUTION_TAGS:-hello-world}"
